### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by ImYenil** [mcsv-kr/mcsv-client#2]
![image](https://github.com/user-attachments/assets/355ec6c7-5a79-45f6-a33c-79e1a60f6e8c)

이거 어떻게 고치나요?

**Comment by Alex4386** [comment]
@Baw-Appie PING
서버측 StackTrace 자료도 필요합니다.
올려주시면 감사하겠습니다.

**Comment by ImYenil** [comment]
> @Baw-Appie PING 서버측 StackTrace 자료도 필요합니다. 올려주시면 감사하겠습니다.

해결했습니다
